---
- hosts: dockerhost
  tasks:
    - name: stop existing container
      command: docker stop regapp_server
      ignore_errors: yes

    - name: remove stopped container
      command: docker rm regapp_server
      ignore_errors: yes

    - name: delete docker image
      command: docker rmi jyothimeena7/regapp    
      ignore_errors: yes

    - name: create container
      command: docker run -d --name regapp_server -p 8082:8080 jyothimeena7/regapp:latest

